language: ruby
sudo: false
cache: bundler
branches:
  only: master
script: bundle exec rake $TASK
env:
- TASK=test
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
matrix:
  include:
  - rvm: 2.3.8 # keep in sync with lowest version
    env: TASK=rubocop
